default_options:
  fit_to_aspect_ratio: false
  tabIndex: 0
  debugMode: false
  debugGridColor: '#437AB2'
  blendTime: 0
  alwaysBlend: false
  autoHideControls: true
  immediateRender: false
  defaultZoomLevel: 0
  opacity: 1
  compositeOperation: ''
  placeholderFillStyle: ''
  degrees: 0
  minZoomLevel: ''
  maxZoomLevel: ''
  homeFillsViewer: false
  panHorizontal: true
  panVertical: true
  constrainDuringPan: false
  wrapHorizontal: false
  wrapVertical: false
  minZoomImageRatio: 0.9
  maxZoomPixelRatio: 1.1
  smoothTileEdgesMinZoom: 1.1
  autoResize: true
  preserveImageSizeOnResize: false
  minScrollDeltaTime: 50
  pixelsPerWheelLine: 40
  visibilityRatio: 0.5
  imageLoaderLimit: 0
  clickTimeThreshold: 300
  clickDistThreshold: 5
  dblClickTimeThreshold: 300
  dblClickDistThreshold: 20
  springStiffness: 6.5
  animationTime: 1.2
  gestureSettingsMouse:
    scrollToZoom: true
    clickToZoom: true
    dblClickToZoom: false
    pinchToZoom: false
    flickEnabled: false
    flickMinSpeed: 120
    flickMomentum: 0.25
    pinchRotate: false
  gestureSettingsTouch:
    scrollToZoom: false
    clickToZoom: false
    dblClickToZoom: true
    pinchToZoom: true
    flickEnabled: true
    flickMinSpeed: 120
    flickMomentum: 0.25
    pinchRotate: false
  gestureSettingsPen:
    scrollToZoom: false
    clickToZoom: true
    dblClickToZoom: false
    pinchToZoom: false
    flickEnabled: false
    flickMinSpeed: 120
    flickMomentum: 0.25
    pinchRotate: false
  gestureSettingsUnknown:
    scrollToZoom: true
    clickToZoom: false
    dblClickToZoom: true
    pinchToZoom: true
    flickEnabled: true
    flickMinSpeed: 120
    flickMomentum: 0.25
    pinchRotate: false
  zoomPerClick: !!float 2
  zoomPerScroll: 1.2
  zoomPerSecond: !!float 1
  showNavigator: false
  navigatorPosition: TOP_RIGHT
  navigatorSizeRatio: 0.2
  navigatorMaintainSizeRatio: false
  navigatorTop: ''
  navigatorLeft: ''
  navigatorHeight: ''
  navigatorWidth: ''
  navigatorAutoResize: true
  navigatorAutoFade: true
  navigatorRotate: true
  controlsFadeDelay: 2000
  controlsFadeLength: 1500
  maxImageCacheCount: 200
  timeout: 30000
  useCanvas: true
  minPixelRatio: 0.5
  mouseNavEnabled: true
  showNavigationControl: true
  navigationControlAnchor: TOP_LEFT
  showZoomControl: true
  showHomeControl: true
  showFullPageControl: true
  showRotationControl: false
  showSequenceControl: true
  sequenceControlAnchor: TOP_LEFT
  navPrevNextWrap: false
  sequenceMode: false
  initialPage: 0
  preserveViewport: false
  preserveOverlays: false
  showReferenceStrip: false
  referenceStripScroll: horizontal
  referenceStripHeight: ''
  referenceStripWidth: ''
  referenceStripPosition: BOTTOM_LEFT
  referenceStripSizeRatio: 0.2
  collectionMode: false
  collectionRows: 3
  collectionColumns: 0
  collectionLayout: horizontal
  collectionTileSize: 800
  collectionTileMargin: 80
  crossOriginPolicy: false
  ajaxWithCredentials: false
  tileSize: 256
iiif_server: 'https://islandora-services-public.lib.asu.edu/cantaloupe/iiif/2'
manifest_view: iiif_manifest
viewer_options:
  fit_to_aspect_ratio: 0
  tabIndex: 0
  debugMode: 0
  debugGridColor: '#437AB2'
  blendTime: 0
  alwaysBlend: 0
  autoHideControls: 1
  immediateRender: 0
  defaultZoomLevel: 0
  opacity: 1
  degrees: 0
  homeFillsViewer: 0
  panHorizontal: 1
  panVertical: 1
  constrainDuringPan: 0
  wrapHorizontal: 0
  wrapVertical: 0
  minZoomImageRatio: 0.9
  maxZoomPixelRatio: 1.1
  smoothTileEdgesMinZoom: 1.1
  autoResize: 1
  preserveImageSizeOnResize: 0
  minScrollDeltaTime: 50
  pixelsPerWheelLine: 40
  visibilityRatio: 0.5
  imageLoaderLimit: 0
  clickTimeThreshold: 300
  clickDistThreshold: 5
  dblClickTimeThreshold: 300
  dblClickDistThreshold: 20
  springStiffness: 6.5
  animationTime: 1.2
  gestureSettingsMouse:
    scrollToZoom: 1
    clickToZoom: 1
    dblClickToZoom: 0
    pinchToZoom: 0
    flickEnabled: 0
    flickMinSpeed: 120
    flickMomentum: 0.25
    pinchRotate: 0
  gestureSettingsTouch:
    scrollToZoom: 0
    clickToZoom: 0
    dblClickToZoom: 1
    pinchToZoom: 1
    flickEnabled: 1
    flickMinSpeed: 120
    flickMomentum: 0.25
    pinchRotate: 0
  gestureSettingsPen:
    scrollToZoom: 0
    clickToZoom: 1
    dblClickToZoom: 0
    pinchToZoom: 0
    flickEnabled: 0
    flickMinSpeed: 120
    flickMomentum: 0.25
    pinchRotate: 0
  gestureSettingsUnknown:
    scrollToZoom: 1
    clickToZoom: 0
    dblClickToZoom: 1
    pinchToZoom: 1
    flickEnabled: 1
    flickMinSpeed: 120
    flickMomentum: 0.25
    pinchRotate: 0
  zoomPerClick: 2
  zoomPerScroll: 1.2
  zoomPerSecond: 1
  controlsFadeDelay: 2000
  controlsFadeLength: 1500
  maxImageCacheCount: 200
  timeout: 30000
  useCanvas: 1
  minPixelRatio: 0.5
  mouseNavEnabled: 1
  sequenceControlAnchor: TOP_LEFT
  navPrevNextWrap: 0
  showNavigator: 0
  navigatorPosition: TOP_RIGHT
  navigatorSizeRatio: 0.2
  navigatorMaintainSizeRatio: 0
  navigatorAutoResize: 1
  navigatorAutoFade: 1
  navigatorRotate: 1
  showNavigationControl: 1
  navigationControlAnchor: TOP_LEFT
  showZoomControl: 1
  showHomeControl: 1
  showFullPageControl: 1
  showRotationControl: 0
  preserveViewport: 1
  preserveOverlays: 0
  showReferenceStrip: 1
  referenceStripScroll: horizontal
  referenceStripPosition: BOTTOM_LEFT
  referenceStripSizeRatio: 0.2
  collectionMode: 0
  collectionRows: 3
  collectionColumns: 0
  collectionLayout: horizontal
  collectionTileSize: 800
  collectionTileMargin: 80
