persistent_identifiers_target_field: field_handle
persistent_identifiers_persister: persistent_identifiers.persister.generic
persistent_identifiers_minter: hdl.minter.hdl
persistent_identifiers_bundles:
  - asu_repository_item
  - collection
  - 0
  - 0
  - 0
persistent_identifiers_map_to_schema_sameas: 0
persistent_identifiers_resolver_base_url: ''
