riprap_mode: remote
riprap_rest_endpoint: 'http://repo-dev.aws.lib.asu.edu/api/fixity'
riprap_local_directory: /path/to/riprap
riprap_local_settings_file: /path/to/riprap/settings.yml
execute_riprap_in_cron: 0
number_of_events: '10'
gemini_rest_endpoint: 'http://10.192.36.190/gemini'
use_drupal_urls: 0
log_riprap_warnings: 1
use_sample_failed_fixity_events: 0
fixity_terms: '16'
fixity_content_type: article
user_name: admin
user_pass: ''
